config/routes.rb
Mailer::Application.routes.draw do
  resources :people
  root :to => 'home#index'
  resource :contact_forms
end

app/models/contact_form.rb
class ContactForm
  include ActiveAttr::Model
  include ActiveAttr::TypecastedAttributes

  attribute :rol, default: 'attendees'
  attribute :message
  attribute :subject
  attribute :welcome, type: Boolean

  validates_presence_of :message, :rol, :subject

  def send_it
    if valid?
      GenericMailer.send_common_email(self)
    end
  end
end

app/models/person.rb
class Person
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :rol, type: String, default: 'assistant'
  field :email, type: String
  field :gender
  field :welcome_sent, type: Boolean, default: false

  validates_presence_of :name, :rol, :email
  validates_format_of :email, :with => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  scope :by_rol, lambda{|rol| where(rol: rol)}

  def first_name
    name.present? ? name.split(' ')[0].capitalize : ''
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  http_basic_authenticate_with name: 'cali-ruby', password: ENV['ACCESS_KEY'] if Rails.env == 'production'
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController

  def new
    @contact_form = ContactForm.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact_form }
    end
  end

  def create
    @contact_form = ContactForm.new(params[:contact_form])

    respond_to do |format|
      if @contact_form.send_it
        format.html { redirect_to root_path, notice: 'message was send successfully'}
        format.json { render json: @contact_form, status: :created, location: @contact_form }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact_form.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new person_params

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes person_params
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private

  def person_params
    params.require(:person).permit(:name, :rol, :gender, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/contact_forms/_contact_form.html.haml
.contact-form
  %h3 Contact us
  = simple_form_for @contact_form do |f|
    - if @contact_form.errors.any?
      #error_explanation
        %h2= "#{pluralize(@contact_form.errors.count, 'error')} prohibited this document from being saved:"
        %ul
          - @contact_form.errors.full_messages.each do |msg|
            %li= msg
    .form-inputs
      .row-fluid
        .span12
          = f.input :rol, required: true, label: false, autofocus: true, collection: %w(assistant coach admin attendant) , placeholder: t(:rol_placeholder)
          = f.input :subject, required: true, placeholder: t(:email_placeholder)
          = f.input :welcome, as: :boolean
          = f.input :message, as: :text, label: false, placeholder: t(:message_placeholder)
      .row-fluid
        .span12
          .form-actions
            = f.submit :submit

app/views/contact_forms/new.html.haml
= render 'contact_forms/contact_form'
%br
= link_to 'Back to home', root_path

app/views/home/index.html.haml
%h1 Main Page

%h3 Persons
= link_to 'People manage', people_path
%br
%h3 Send Bulk Email
= link_to 'From to', new_contact_forms_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Mailer
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/people/_form.html.haml
= form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :rol
    = f.select :rol, %w(assistant coach admin attendant)
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :gender
    = f.select :gender, %w(f m)
  .actions
    = f.submit 'Save'

app/views/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', @person
\|
= link_to 'Back', people_path

app/views/people/index.html.haml
%h1 Listing people

%table
  %tr
    %th Name
    %th Rol
    %th Email
    %th
    %th
    %th

  - @people.each do |person|
    %tr
      %td= person.name
      %td= person.rol
      %td= person.email
      %td= link_to 'Show', person
      %td= link_to 'Edit', edit_person_path(person)
      %td= link_to 'Destroy', person, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Person', new_person_path
%br
= link_to 'Back to home', root_path

app/views/people/new.html.haml
%h1 New person

= render 'form'

= link_to 'Back', people_path

app/views/people/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @person.name
%p
  %b Rol:
  = @person.rol
%p
  %b Email:
  = @person.email

= link_to 'Edit', edit_person_path(@person)
\|
= link_to 'Back', people_path